version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "03:00"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine
    - 15.11.0.pre.alpine
    - 15.12.0.pre.alpine
    - 15.14.0.pre.alpine
    - 15.7.0.pre.alpine
    - 15.8.0.pre.alpine
  rebase-strategy: disabled
